### ISSUE TITLE
Issue with Annotations

### ISSUE THREAD

**Issue by yuriydzobak** [VictoriaMetrics/grafana-datasource#154] opened 2024-04-15 15:08 UTC
Hi
Grafana version is 10.1.5
plugin version  0.7.0
I have mentioned that annotations were broken, but I don't remember after which version or it was worked before i starts to use plugin

When the DataSource is a variable type, Grafana doesn't put the variable value into the address to the data source, which causes a failure.

Please take a look at the screenshot.
![grafana-annotations](https://github.com/VictoriaMetrics/grafana-datasource/assets/70581130/90644075-a2f5-4e18-b51c-902181d99171)

Also, if i used DataSource Name not variable type, but the query doesn't support variables and doesn't provide any events, issue, console log or POD logs
if query is in format `up{dc="$VAR"}` then empty if i used `up{dc="foo"}` then it works
var DC is having values

![image](https://github.com/VictoriaMetrics/grafana-datasource/assets/70581130/50cbbd75-28ab-45b6-bd8c-5bd919d4ef45)

![image](https://github.com/VictoriaMetrics/grafana-datasource/assets/70581130/67748697-df94-4a30-b0e7-dd6070381a24)

Thanks for help

**Comment by Loori-R** [comment] 2024-04-15 15:31
Duplicate of https://github.com/VictoriaMetrics/grafana-datasource/issues/146
This issue has been fixed in datasource starting from [v0.8.0](https://github.com/VictoriaMetrics/grafana-datasource/releases/tag/v0.8.0).

**Comment by Loori-R** [comment] 2024-04-15 15:31
Duplicate of https://github.com/VictoriaMetrics/grafana-datasource/issues/146
This issue has been fixed in datasource starting from [v0.8.0](https://github.com/VictoriaMetrics/grafana-datasource/releases/tag/v0.8.0).

**Closed by Loori-R** 2024-04-15 15:31 UTC
